### ISSUE TITLE
Use volumes to keep user data

### ISSUE THREAD

**Issue by Takeno** [pauleve/docker-mtgo#6]
I've studied the MTGO directories, and it can be useful find a way to save user changes without commit new container images (which is not a good practice, imho).

I've found MTGO installation files in
`/home/wine/.wine/drive_c/users/wine/Local Settings/Application Data/Apps/2.0/4ZCGNGV8.Q6C/PQ0L852P.JOD` where `4ZCGNGV8.Q6C/PQ0L852P.JOD` are random strings.

The idea is use a persistent volume to store MTGO files and make the startup faster.

I used `docker-compose` to more practice, but it's just a mapping of `docker-run` options:

```yaml
version: "2"

services:
  mtgo:
    build: ./
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - data:/home/wine/.wine/drive_c/users/wine/Local Settings/Application Data
    network_mode: host
    stdin_open: true
    tty: true

volumes:
  data: {}
```

In this way, on first run it ask me updates and license confirmation. The second run I got the login screen with my username already there.
